SELECT * FROM PCLIENTE - TABELA DE CLIENTE
SELECT * FROM PCPRODUT - TABELA DE PRODUTO
SELECT * FROM PCFORNEC - TABELA FORNECEDOR
SELECT * FROM PCNFSAID - TABELA NF SAIDA
SELECT * FROM PCNFENT  - TABELA NF ENTRADA


